import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { draftMode } from 'next/headers'
import ContentfulPreviewProvider from '@/components/ContentfulPreviewProvider'
import '../globals.css'
import { ExitPreviewButton } from '@/components/ExitPreviewButton'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  const { isEnabled } = await draftMode()
  const { lang } = await params

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ContentfulPreviewProvider isEnabled={isEnabled} locale={lang}>
          {children}
        </ContentfulPreviewProvider>
        {isEnabled && <ExitPreviewButton />}
      </body>
    </html>
  )
}
