import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { draftMode } from 'next/headers'
import { GoogleTagManager } from '@next/third-parties/google'
import { getGlobalSettingsData } from '@/lib/contentful/contentfulService'
import { ContentfulPreviewProvider, ExitPreviewButton } from '@/components/Global/LivePreview'
import PersonalizationWrapper from '@/components/Global/Personalization/PersonalizationWrapper'
import '../globals.css'
import TrackPage from '@/components/Global/Personalization/TrackPage'
import Header from '@/components/Global/Header'
import AlertBanner from '@/components/Global/AlertBanner/AlertBanner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  const { isEnabled } = await draftMode()
  const { lang } = await params
  const { data: globalSettingsData } = await getGlobalSettingsData(lang)
  const GTM_ID = (globalSettingsData?.fields?.gtmId as string) || ''

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {GTM_ID && <GoogleTagManager gtmId={GTM_ID} />}
        <PersonalizationWrapper>
          <TrackPage />
          <main id="main">
            <ContentfulPreviewProvider isEnabled={isEnabled} locale={lang}>
              <AlertBanner />
              <Header />
              {children}
            </ContentfulPreviewProvider>
            {isEnabled && <ExitPreviewButton />}
          </main>
        </PersonalizationWrapper>
      </body>
    </html>
  )
}
