import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { draftMode } from 'next/headers'
import { GoogleTagManager } from '@next/third-parties/google'
import { getGlobalSettingsData } from '@/lib/contentful/contentfulService'
import { ContentfulPreviewProvider, ExitPreviewButton } from '@/components/Global/LivePreview'
import '../globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  const { isEnabled } = await draftMode()
  const { lang } = await params
  const { data: globalSettingsData } = await getGlobalSettingsData(lang)
  const GTM_ID = (globalSettingsData?.fields?.gtmId as string) || ''

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {GTM_ID && <GoogleTagManager gtmId={GTM_ID} />}
        <main id="main">
          <ContentfulPreviewProvider isEnabled={isEnabled} locale={lang}>
            {children}
          </ContentfulPreviewProvider>
          {isEnabled && <ExitPreviewButton />}
        </main>
      </body>
    </html>
  )
}
